/*
 * Heimdall
 *
 * # Introduction    The Heimdall backchannel API is a [RESTful](https://wikipedia.org/wiki/Representational_state_transfer) API that allows you to do authorizations, manage sessions, do CRUD on various objects, etc.          
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HeimdallClient.Client.OpenAPIDateConverter;

namespace HeimdallClient.Model
{
    /// <summary>
    /// LogoutResponse
    /// </summary>
    [DataContract(Name = "LogoutResponse")]
    public partial class LogoutResponse : IEquatable<LogoutResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogoutResponse" /> class.
        /// </summary>
        /// <param name="finalResponse">finalResponse.</param>
        /// <param name="error">error.</param>
        /// <param name="logoutPrompt">logoutPrompt.</param>
        public LogoutResponse(LogoutFinalResponse finalResponse = default(LogoutFinalResponse), LogoutError error = default(LogoutError), LogoutPrompt logoutPrompt = default(LogoutPrompt))
        {
            this.FinalResponse = finalResponse;
            this.Error = error;
            this.LogoutPrompt = logoutPrompt;
        }

        /// <summary>
        /// Gets or Sets FinalResponse
        /// </summary>
        [DataMember(Name = "final_response", EmitDefaultValue = false)]
        public LogoutFinalResponse FinalResponse { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public LogoutError Error { get; set; }

        /// <summary>
        /// Gets or Sets LogoutPrompt
        /// </summary>
        [DataMember(Name = "logout_prompt", EmitDefaultValue = false)]
        public LogoutPrompt LogoutPrompt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogoutResponse {\n");
            sb.Append("  FinalResponse: ").Append(FinalResponse).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  LogoutPrompt: ").Append(LogoutPrompt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LogoutResponse);
        }

        /// <summary>
        /// Returns true if LogoutResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LogoutResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LogoutResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FinalResponse == input.FinalResponse ||
                    (this.FinalResponse != null &&
                    this.FinalResponse.Equals(input.FinalResponse))
                ) && 
                (
                    this.Error == input.Error ||
                    (this.Error != null &&
                    this.Error.Equals(input.Error))
                ) && 
                (
                    this.LogoutPrompt == input.LogoutPrompt ||
                    (this.LogoutPrompt != null &&
                    this.LogoutPrompt.Equals(input.LogoutPrompt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FinalResponse != null)
                {
                    hashCode = (hashCode * 59) + this.FinalResponse.GetHashCode();
                }
                if (this.Error != null)
                {
                    hashCode = (hashCode * 59) + this.Error.GetHashCode();
                }
                if (this.LogoutPrompt != null)
                {
                    hashCode = (hashCode * 59) + this.LogoutPrompt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
