/*
 * Heimdall
 *
 * # Introduction    The Heimdall backchannel API is a [RESTful](https://wikipedia.org/wiki/Representational_state_transfer) API that allows you to do authorizations, manage sessions, do CRUD on various objects, etc.          
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HeimdallClient.Client.OpenAPIDateConverter;

namespace HeimdallClient.Model
{
    /// <summary>
    /// RequestedClaims
    /// </summary>
    [DataContract(Name = "RequestedClaims")]
    public partial class RequestedClaims : IEquatable<RequestedClaims>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestedClaims" /> class.
        /// </summary>
        /// <param name="userinfo">userinfo.</param>
        /// <param name="idToken">idToken.</param>
        public RequestedClaims(Dictionary<string, RequestedClaim> userinfo = default(Dictionary<string, RequestedClaim>), Dictionary<string, RequestedClaim> idToken = default(Dictionary<string, RequestedClaim>))
        {
            this.Userinfo = userinfo;
            this.IdToken = idToken;
        }

        /// <summary>
        /// Gets or Sets Userinfo
        /// </summary>
        [DataMember(Name = "userinfo", EmitDefaultValue = true)]
        public Dictionary<string, RequestedClaim> Userinfo { get; set; }

        /// <summary>
        /// Gets or Sets IdToken
        /// </summary>
        [DataMember(Name = "id_token", EmitDefaultValue = true)]
        public Dictionary<string, RequestedClaim> IdToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestedClaims {\n");
            sb.Append("  Userinfo: ").Append(Userinfo).Append("\n");
            sb.Append("  IdToken: ").Append(IdToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestedClaims);
        }

        /// <summary>
        /// Returns true if RequestedClaims instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestedClaims to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestedClaims input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Userinfo == input.Userinfo ||
                    this.Userinfo != null &&
                    input.Userinfo != null &&
                    this.Userinfo.SequenceEqual(input.Userinfo)
                ) && 
                (
                    this.IdToken == input.IdToken ||
                    this.IdToken != null &&
                    input.IdToken != null &&
                    this.IdToken.SequenceEqual(input.IdToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Userinfo != null)
                {
                    hashCode = (hashCode * 59) + this.Userinfo.GetHashCode();
                }
                if (this.IdToken != null)
                {
                    hashCode = (hashCode * 59) + this.IdToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
