version: "3.9"

services:
  heimdall:
    image: "birkmose/oidc:1.0.0-alpha.1"
    command: -c /config
    volumes:
      - ./HeimdallConfig:/config
    ports: 
      - 8080:8080
  oidc_demo_client:
    volumes:
      - ./OidcDemoClientConfig:/usr/share/nginx/html/config
    image: birkmose/oidc-demo-client
    ports: 
      - 3000:80
  basic_idp_example:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build: ./BasicIdpExample
    ports: 
      - 9080:80

