/*
 * Heimdall
 *
 * # Introduction    The Heimdall backchannel API is a [RESTful](https://wikipedia.org/wiki/Representational_state_transfer) API that allows you to do authorizations, manage sessions, do CRUD on various objects, etc.          
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = heimdall_client.Client.OpenAPIDateConverter;

namespace heimdall_client.Model
{
    /// <summary>
    /// Additional claims you to include in the generated token(s)
    /// </summary>
    [DataContract(Name = "AdditionalClaims")]
    public partial class AdditionalClaims : IEquatable<AdditionalClaims>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalClaims" /> class.
        /// </summary>
        /// <param name="accessToken">Claims to be included in the generated access token (if generated - depends on the grant type)..</param>
        /// <param name="idToken">Claims to be included in the generated id token (if generated - depends on the grant type)..</param>
        public AdditionalClaims(Dictionary<string, Object> accessToken = default(Dictionary<string, Object>), Dictionary<string, Object> idToken = default(Dictionary<string, Object>))
        {
            this.AccessToken = accessToken;
            this.IdToken = idToken;
        }

        /// <summary>
        /// Claims to be included in the generated access token (if generated - depends on the grant type).
        /// </summary>
        /// <value>Claims to be included in the generated access token (if generated - depends on the grant type).</value>
        [DataMember(Name = "access_token", EmitDefaultValue = true)]
        public Dictionary<string, Object> AccessToken { get; set; }

        /// <summary>
        /// Claims to be included in the generated id token (if generated - depends on the grant type).
        /// </summary>
        /// <value>Claims to be included in the generated id token (if generated - depends on the grant type).</value>
        [DataMember(Name = "id_token", EmitDefaultValue = true)]
        public Dictionary<string, Object> IdToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdditionalClaims {\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("  IdToken: ").Append(IdToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AdditionalClaims);
        }

        /// <summary>
        /// Returns true if AdditionalClaims instances are equal
        /// </summary>
        /// <param name="input">Instance of AdditionalClaims to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdditionalClaims input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccessToken == input.AccessToken ||
                    this.AccessToken != null &&
                    input.AccessToken != null &&
                    this.AccessToken.SequenceEqual(input.AccessToken)
                ) && 
                (
                    this.IdToken == input.IdToken ||
                    this.IdToken != null &&
                    input.IdToken != null &&
                    this.IdToken.SequenceEqual(input.IdToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccessToken != null)
                {
                    hashCode = (hashCode * 59) + this.AccessToken.GetHashCode();
                }
                if (this.IdToken != null)
                {
                    hashCode = (hashCode * 59) + this.IdToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
